List<Map<String, String>> currencySymbol = [
  {"name": "US Dollar", "symbol": "\$"},
  {"name": "Euro", "symbol": "€"},
  {"name": "Indian Rupee", "symbol": "₹"},
  {"name": "Pound", "symbol": "£"},
  {"name": "Yen", "symbol": "¥"},
  {"name": "Won", "symbol": "₩"},
  {"name": "Ruble", "symbol": "₽"},
  {"name": "Peso", "symbol": "₱"},
  {"name": "Franc", "symbol": "CHF"},
  {"name": "Ringgit", "symbol": "RM"},
  {"name": "Baht", "symbol": "฿"},
  {"name": "Lira", "symbol": "₺"},
  {"name": "Dong", "symbol": "₫"},
  {"name": "Taka", "symbol": "৳"},
  {"name": "Riyal", "symbol": "﷼"},
];
